name: Fetch OpenAPI Specification from Gateway and Build Docs

on:
  push:
    branches:
      - refactor-api-docs-generation
  workflow_dispatch:
#  repository_dispatch:
#    types: [trigger-build]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-update-docs:  # More descriptive name for the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout docs-api-official repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download openapi.yaml file
        run: |
          curl -H "Authorization: token ${{ secrets.CI_ACTIONS_PAT }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L "https://api.github.com/repos/ecolytiq/gateway/contents/src/main/resources/openapi.yaml?ref=main" \
               -o openapi.yaml

      - name: Setup variables using Environment Files
        run: |
          echo "BRANCH_NAME=update-openapi-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          echo "DATE_TIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Execute build.sh script
        run: bash build.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update OpenAPI spec and build output"
          title: "Auto-update OpenAPI documentation [${{ env.DATE_TIME }}]"
          body: |
            This PR updates the OpenAPI documentation.
            
            Preview: [https://htmlpreview.github.io/?https://github.com/ecolytiq/docs-api-official/blob/${{ env.BRANCH_NAME }}/index.html](https://htmlpreview.github.io/?https://github.com/ecolytiq/docs-api-official/blob/${{ env.BRANCH_NAME }}/index.html)
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          signoff: false
